name: build release
on:
 push:
  branches:
   - main
permissions: write-all
jobs:
 build-lib:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - uses: pnpm/action-setup@v4
     with:
      version: 8
   - name: 配置 Node 环境
     uses: actions/setup-node@v4
     with:
      node-version: 'latest'
      cache: 'pnpm'
   - name: 安装 PNPM
     run: npm i -g pnpm
   - name: 安装依赖
     run: pnpm install --no-frozen-lockfile
   - name: 构建
     run: pnpm build-lib
   - name: 创建文件夹
     run: mkdir ./release
   - name: 打包
     run: tar czvf ./release/source.tar ./dist
   - name: 发布到release分支
     uses: crazy-max/ghaction-github-pages@v4
     with:
      target_branch: release
      build_dir: ./release
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
